networks:
  app:

services:
  client:
    build: ./client
    networks:
      - app
    ports:
      - 7860:7860
    depends_on:
      - api
    command: ["python", "/client", "app_gradio.py"]

  api:
    build: ./api
    networks:
      - app
    ports:
      - 8000:8000

