version: '3.7'

networks:
  app:


services:
  model_api:
    build: ./api
    networks:
      - app
    ports:
      - 8000:8000


  client:
    build: ./client
    networks:
      - app
    ports:
      - 7860:7860
    depends_on:
      - model_api


